<?php

namespace App\Enums;

use MadWeb\Enum\Enum;

/**
 * List of all currencies
 *
 * @method static CurrenciesEnum ALL()
 * @method static CurrenciesEnum AFN()
 * @method static CurrenciesEnum ARS()
 * @method static CurrenciesEnum AWG()
 * @method static CurrenciesEnum AUD()
 * @method static CurrenciesEnum AZN()
 * @method static CurrenciesEnum BSD()
 * @method static CurrenciesEnum BBD()
 * @method static CurrenciesEnum BDT()
 * @method static CurrenciesEnum BYN()
 * @method static CurrenciesEnum BYR()
 * @method static CurrenciesEnum BZD()
 * @method static CurrenciesEnum BMD()
 * @method static CurrenciesEnum BOB()
 * @method static CurrenciesEnum BAM()
 * @method static CurrenciesEnum BWP()
 * @method static CurrenciesEnum BGN()
 * @method static CurrenciesEnum BRL()
 * @method static CurrenciesEnum BND()
 * @method static CurrenciesEnum KHR()
 * @method static CurrenciesEnum CAD()
 * @method static CurrenciesEnum KYD()
 * @method static CurrenciesEnum CLP()
 * @method static CurrenciesEnum CNY()
 * @method static CurrenciesEnum COP()
 * @method static CurrenciesEnum CRC()
 * @method static CurrenciesEnum HRK()
 * @method static CurrenciesEnum CUP()
 * @method static CurrenciesEnum CZK()
 * @method static CurrenciesEnum DKK()
 * @method static CurrenciesEnum DOP()
 * @method static CurrenciesEnum XCD()
 * @method static CurrenciesEnum EGP()
 * @method static CurrenciesEnum SVC()
 * @method static CurrenciesEnum EEK()
 * @method static CurrenciesEnum EUR()
 * @method static CurrenciesEnum FKP()
 * @method static CurrenciesEnum FJD()
 * @method static CurrenciesEnum GHC()
 * @method static CurrenciesEnum GIP()
 * @method static CurrenciesEnum GTQ()
 * @method static CurrenciesEnum GGP()
 * @method static CurrenciesEnum GYD()
 * @method static CurrenciesEnum HNL()
 * @method static CurrenciesEnum HKD()
 * @method static CurrenciesEnum HUF()
 * @method static CurrenciesEnum ISK()
 * @method static CurrenciesEnum INR()
 * @method static CurrenciesEnum IDR()
 * @method static CurrenciesEnum IRR()
 * @method static CurrenciesEnum IMP()
 * @method static CurrenciesEnum ILS()
 * @method static CurrenciesEnum JMD()
 * @method static CurrenciesEnum JPY()
 * @method static CurrenciesEnum JEP()
 * @method static CurrenciesEnum KZT()
 * @method static CurrenciesEnum KPW()
 * @method static CurrenciesEnum KRW()
 * @method static CurrenciesEnum KGS()
 * @method static CurrenciesEnum LAK()
 * @method static CurrenciesEnum LVL()
 * @method static CurrenciesEnum LBP()
 * @method static CurrenciesEnum LRD()
 * @method static CurrenciesEnum LTL()
 * @method static CurrenciesEnum MKD()
 * @method static CurrenciesEnum MYR()
 * @method static CurrenciesEnum MUR()
 * @method static CurrenciesEnum MXN()
 * @method static CurrenciesEnum MNT()
 * @method static CurrenciesEnum MZN()
 * @method static CurrenciesEnum NAD()
 * @method static CurrenciesEnum NPR()
 * @method static CurrenciesEnum ANG()
 * @method static CurrenciesEnum NZD()
 * @method static CurrenciesEnum NIO()
 * @method static CurrenciesEnum NGN()
 * @method static CurrenciesEnum NOK()
 * @method static CurrenciesEnum OMR()
 * @method static CurrenciesEnum PKR()
 * @method static CurrenciesEnum PAB()
 * @method static CurrenciesEnum PYG()
 * @method static CurrenciesEnum PEN()
 * @method static CurrenciesEnum PHP()
 * @method static CurrenciesEnum PLN()
 * @method static CurrenciesEnum QAR()
 * @method static CurrenciesEnum RON()
 * @method static CurrenciesEnum RUB()
 * @method static CurrenciesEnum SHP()
 * @method static CurrenciesEnum SAR()
 * @method static CurrenciesEnum RSD()
 * @method static CurrenciesEnum SCR()
 * @method static CurrenciesEnum SGD()
 * @method static CurrenciesEnum SBD()
 * @method static CurrenciesEnum SOS()
 * @method static CurrenciesEnum ZAR()
 * @method static CurrenciesEnum LKR()
 * @method static CurrenciesEnum SEK()
 * @method static CurrenciesEnum CHF()
 * @method static CurrenciesEnum SRD()
 * @method static CurrenciesEnum SYP()
 * @method static CurrenciesEnum TWD()
 * @method static CurrenciesEnum THB()
 * @method static CurrenciesEnum TTD()
 * @method static CurrenciesEnum TRL()
 * @method static CurrenciesEnum TVD()
 * @method static CurrenciesEnum UAH()
 * @method static CurrenciesEnum GBP()
 * @method static CurrenciesEnum USD()
 * @method static CurrenciesEnum UYU()
 * @method static CurrenciesEnum UZS()
 * @method static CurrenciesEnum VEF()
 * @method static CurrenciesEnum VND()
 * @method static CurrenciesEnum YER()
 * @method static CurrenciesEnum ZWD()
 */
final class CurrenciesEnum extends Enum
{
    public const __default = self::EUR;

    public const ALL = 'ALL';
    public const AFN = 'AFN';
    public const ARS = 'ARS';
    public const AWG = 'AWG';
    public const AUD = 'AUD';
    public const AZN = 'AZN';
    public const BSD = 'BSD';
    public const BBD = 'BBD';
    public const BDT = 'BDT';
    public const BYN = 'BYN';
    public const BYR = 'BYR';
    public const BZD = 'BZD';
    public const BMD = 'BMD';
    public const BOB = 'BOB';
    public const BAM = 'BAM';
    public const BWP = 'BWP';
    public const BGN = 'BGN';
    public const BRL = 'BRL';
    public const BND = 'BND';
    public const KHR = 'KHR';
    public const CAD = 'CAD';
    public const KYD = 'KYD';
    public const CLP = 'CLP';
    public const CNY = 'CNY';
    public const COP = 'COP';
    public const CRC = 'CRC';
    public const HRK = 'HRK';
    public const CUP = 'CUP';
    public const CZK = 'CZK';
    public const DKK = 'DKK';
    public const DOP = 'DOP';
    public const XCD = 'XCD';
    public const EGP = 'EGP';
    public const SVC = 'SVC';
    public const EEK = 'EEK';
    public const EUR = 'EUR';
    public const FKP = 'FKP';
    public const FJD = 'FJD';
    public const GHC = 'GHC';
    public const GIP = 'GIP';
    public const GTQ = 'GTQ';
    public const GGP = 'GGP';
    public const GYD = 'GYD';
    public const HNL = 'HNL';
    public const HKD = 'HKD';
    public const HUF = 'HUF';
    public const ISK = 'ISK';
    public const INR = 'INR';
    public const IDR = 'IDR';
    public const IRR = 'IRR';
    public const IMP = 'IMP';
    public const ILS = 'ILS';
    public const JMD = 'JMD';
    public const JPY = 'JPY';
    public const JEP = 'JEP';
    public const KZT = 'KZT';
    public const KPW = 'KPW';
    public const KRW = 'KRW';
    public const KGS = 'KGS';
    public const LAK = 'LAK';
    public const LVL = 'LVL';
    public const LBP = 'LBP';
    public const LRD = 'LRD';
    public const LTL = 'LTL';
    public const MKD = 'MKD';
    public const MYR = 'MYR';
    public const MUR = 'MUR';
    public const MXN = 'MXN';
    public const MNT = 'MNT';
    public const MZN = 'MZN';
    public const NAD = 'NAD';
    public const NPR = 'NPR';
    public const ANG = 'ANG';
    public const NZD = 'NZD';
    public const NIO = 'NIO';
    public const NGN = 'NGN';
    public const NOK = 'NOK';
    public const OMR = 'OMR';
    public const PKR = 'PKR';
    public const PAB = 'PAB';
    public const PYG = 'PYG';
    public const PEN = 'PEN';
    public const PHP = 'PHP';
    public const PLN = 'PLN';
    public const QAR = 'QAR';
    public const RON = 'RON';
    public const RUB = 'RUB';
    public const SHP = 'SHP';
    public const SAR = 'SAR';
    public const RSD = 'RSD';
    public const SCR = 'SCR';
    public const SGD = 'SGD';
    public const SBD = 'SBD';
    public const SOS = 'SOS';
    public const ZAR = 'ZAR';
    public const LKR = 'LKR';
    public const SEK = 'SEK';
    public const CHF = 'CHF';
    public const SRD = 'SRD';
    public const SYP = 'SYP';
    public const WD = 'TWD';
    public const THB = 'THB';
    public const TTD = 'TTD';
    public const TRL = 'TRL';
    public const TVD = 'TVD';
    public const UAH = 'UAH';
    public const GBP = 'GBP';
    public const USD = 'USD';
    public const UYU = 'UYU';
    public const UZS = 'UZS';
    public const VEF = 'VEF';
    public const VND = 'VND';
    public const YER = 'YER';
    public const ZWD = 'ZWD';
}
